// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_3imnHwBMqoBmsO3ua-LWypd9xSMbEY',
    appId: '1:810710894411:android:03749a3ee7205be57d8ace',
    messagingSenderId: '810710894411',
    projectId: 'sehaty-68b9f',
    storageBucket: 'sehaty-68b9f.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXxd7LVSb7g_x4f-A8VUQoazHfXeSAeg',
    appId: '1:810710894411:web:22f94445208dc2d07d8ace',
    messagingSenderId: '810710894411',
    projectId: 'sehaty-68b9f',
    authDomain: 'sehaty-68b9f.firebaseapp.com',
    storageBucket: 'sehaty-68b9f.firebasestorage.app',
    measurementId: 'G-S7X1BT68KY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN60YwAm9UqU5y_ud-T47RvuCWzpdI-Kk',
    appId: '1:810710894411:ios:5eff4d6a106acf4e7d8ace',
    messagingSenderId: '810710894411',
    projectId: 'sehaty-68b9f',
    storageBucket: 'sehaty-68b9f.firebasestorage.app',
    iosClientId: '810710894411-6b8iq157om37fuufl4bp8a0t7sfsafmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sehaty',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN60YwAm9UqU5y_ud-T47RvuCWzpdI-Kk',
    appId: '1:810710894411:ios:5eff4d6a106acf4e7d8ace',
    messagingSenderId: '810710894411',
    projectId: 'sehaty-68b9f',
    storageBucket: 'sehaty-68b9f.firebasestorage.app',
    iosClientId: '810710894411-6b8iq157om37fuufl4bp8a0t7sfsafmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sehaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCXxd7LVSb7g_x4f-A8VUQoazHfXeSAeg',
    appId: '1:810710894411:web:0638c09307ecc6987d8ace',
    messagingSenderId: '810710894411',
    projectId: 'sehaty-68b9f',
    authDomain: 'sehaty-68b9f.firebaseapp.com',
    storageBucket: 'sehaty-68b9f.firebasestorage.app',
    measurementId: 'G-PHPWHNPSSE',
  );
}
